<?php

namespace app\api\controller;

class User extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        self::$class = self::$namespace . self::$class;
        $this->requestClassExists(self::$class);
    }

    /**
     * 用户登录接口
     * @return string
     */
    public function login()
    {
        if (get_user(self::$param['token'])) {
            self::$code = 402;
            self::$msg = '您已登录，请勿重新登录！';
            return $this->returnData();
        }
        $class = new self::$class(self::$param);
        list(self::$code, self::$msg, self::$data) = $class->login();
        return $this->returnData();
    }
}
